site_name: Open Qsyn
site_url: https://qsyn.github.io.
#repo_url: https://github.com/qsyn/qsyn.github.io.
#edit_uri: ""
site_description: "Matlab based modern open source toolbox for QFT control synthesis"